//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class ___VARIABLE_sceneName___CollectionViewCell: UICollectionViewCell {

    static let identifier = "___VARIABLE_sceneName___CollectionViewCell"

    // @IBOutlet weak var iconImageView: UIImageView!
    // @IBOutlet weak var titleLabel:    UILabel!
    // @IBOutlet weak var contentLabel:  UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        // Configure cell initial settings
    }

    var displayedSomething: ___VARIABLE_sceneName___Scene.___VARIABLE_useCase___.ViewModel.DisplayedSomething! {
        didSet {
            // Configure cell from object
            // iconImageView.image = displayedSomething.image
        }
    }

}
