//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ___VARIABLE_sceneName___ViewController {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ___VARIABLE_sceneName___Configurator.configure(viewController: self)
    }
    
    static func instantiate() -> ___VARIABLE_sceneName___ViewController {
        let storyboard = UIStoryboard(name: "___VARIABLE_sceneName___", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! ___VARIABLE_sceneName___ViewController
        return viewController
    }
    
}

class ___VARIABLE_sceneName___Configurator {
    
    // MARK: - Configuration
    
    static func configure(viewController: ___VARIABLE_sceneName___ViewController) {
        
        let presenter = ___VARIABLE_sceneName___Presenter()
        presenter.viewController = viewController
        
        let interactor = ___VARIABLE_sceneName___Interactor()
        interactor.presenter = presenter
        
        let router = ___VARIABLE_sceneName___Router()
        router.viewController = viewController
        router.interactor = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
    
}
