//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates.
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ___FILEBASENAMEASIDENTIFIER___Interactor {
    
    var presenter: ___FILEBASENAMEASIDENTIFIER___Presenter!
    var worker: ___FILEBASENAMEASIDENTIFIER___Worker!
    
    // MARK: - Object variables
    
    // var loadAction: loadAction!
    
    // MARK: - Business logic
    
    func fetchSomething(request: ___FILEBASENAMEASIDENTIFIER___.Something.Request) {
        // NOTE: Create some Worker to do the work
        
        ___FILEBASENAMEASIDENTIFIER___Worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = ___FILEBASENAMEASIDENTIFIER___.Something.Response()
        presenter.presentSomething(response: response)
    }
    
}
