//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum ___VARIABLE_sceneName___Scene {

    enum ___VARIABLE_useCase___ {

        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }

    }

}
