//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates.
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ___FILEBASENAMEASIDENTIFIER___Presenter {
    
    weak var viewController: ___FILEBASENAMEASIDENTIFIER___ViewController!
    
    // MARK: - Presentation logic
    
    func presentSomething(response: ___FILEBASENAMEASIDENTIFIER___.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = ___FILEBASENAMEASIDENTIFIER___.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
    
}
